import type { Metadata } from 'next';
import Link from 'next/link';
import SiteFooter from '../../components/SiteFooter';
import SiteHeader from '../../components/SiteHeader';
import data, { EM_DASHES_SHOWN_AS_HYPHENS, count, num, usd } from './data';
import type { Brief, BriefItem, Citation, Item, ScoreRow } from './data';
import { Chip, FIELDS, ItemView, Panel, Planted, Pre, Source, Tally, kinds, shortfalls, tallies, unchecked } from './parts';
import type { EvidenceState } from './parts';

const TITLE = 'Walkthrough: from the record to the decision | Intellumia';
const DESCRIPTION =
  'A fictional company, followed from raw email, chat and meetings to a one-page decision brief, with every output shown beside the source text it came from, and what each piece missed.';

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: '/lab/walkthrough' },
  openGraph: {
    type: 'article',
    images: [{ url: '/social/og-default.png', width: 1200, height: 630, alt: 'Intellumia: Intelligence is free. Judgement is the moat.' }],
    url: 'https://intellumia.com/lab/walkthrough',
    title: TITLE,
    description: DESCRIPTION,
  },
  twitter: { card: 'summary_large_image', images: ['/social/og-default.png'], title: TITLE, description: DESCRIPTION },
};

const S = data.sources;
const F = data.finders;

const FINDERS: { id: string; question: string; read: string; benchmark: string[] }[] = [
  {
    id: 'decision-extractor',
    question: 'What did we decide, who owns it, and why?',
    read: 'every thread: email, chat and meetings',
    benchmark: [
      'Held out on 97 AMI meetings, Claude Sonnet 5 for both: F1 58.9% against 56.8% for a plain prompt under one judge, 54.6% against 54.8% under a second. Read it as a tie; every decision it keeps carries quotes found in the transcript.',
      'Against transcript-analysis-pipeline, an open-source tool, on 60 of the same meetings: it found 80.5% of the reference decisions against 48.9%, but the pipeline’s F1 was higher (61.6% against 57.9%), because it packs several decisions into one sentence.',
      'On an earlier generated organisation it found 8 of 12 planted decisions and reported none of 22 look-alikes, but 44 of the 62 items it called made decisions were commitments, status messages or filler.',
    ],
  },
  {
    id: 'commitment-tracker',
    question: 'Who promised what, by when, and did it happen?',
    read: 'every thread: email, chat and meetings',
    benchmark: [
      'Held out: F1 100% on generated email threads against 85.8% for a plain prompt, with none of 137 non-commitments reported. The threads were generated by the same author as the tracker.',
      'On 97 AMI meetings, a tie: F1 50.8% and 55.8% under two judges, against 51.6% and 49.6%. On threads, six cheaper and free models scored 97.5% to 100% F1.',
    ],
  },
  {
    id: 'risk-finder',
    question: 'What could go wrong, what already has, and who holds it?',
    read: 'every thread: email, chat and meetings',
    benchmark: [
      'Held out: F1 99.0% on generated threads against 90.6% for a plain prompt; it found 84% to 87% of live issues where the plain prompt found 5% to 9%. The threads were generated by the same author as the finder.',
      'On AMI meetings, a tie: F1 58.5% and 49.1% under two judges, against 59.4% and 50.2%.',
    ],
  },
  {
    id: 'gap-finder',
    question: 'What was asked that nobody answered?',
    read: 'email and chat only, because its README says it loses to a plain prompt on meetings',
    benchmark: [
      'Held out: F1 98.8% on generated email threads against 91.3% for a plain prompt. The threads were generated by the same author as the finder.',
      'On meetings it loses: F1 55.7% and 42.0% under two judges, against 61.5% and 52.5%.',
    ],
  },
  {
    id: 'contradiction-detector',
    question: 'Where does the record disagree with itself?',
    read: 'the whole record at once, in time order',
    benchmark: [
      'Held out: F1 99.6% on generated conversations against 96.6% for a plain prompt, with none of 107 look-alikes reported. Those conversations were written by the same author as the detector.',
      'On real Wikipedia passages (WikiContradict) it finds fewer: recall 81.0% against 90.2%. On conversations, two cheaper models matched Sonnet 5.',
    ],
  },
  {
    id: 'expertise-finder',
    question: 'Who knows what, shown in their own words?',
    read: 'email and chat only, because its README says it loses to a plain prompt on meetings',
    benchmark: [
      'Held out: F1 99.8% on generated email threads against 89.2% for a plain prompt, with none of 315 look-alikes credited. The threads were generated by the same author as the finder.',
      'On meetings it loses: F1 62.1% and 63.2% under two judges, against 68.5% and 73.7%.',
    ],
  },
];

// Notes under each finder's counts. Numbers come from the run; the wording explains what the counts mean.
function finderNotes(id: string): string[] {
  const s = F[id]?.score ?? {};
  const n = (k: string) => num(s[k]);
  switch (id) {
    case 'decision-extractor':
      return [
        n('reversals_in_other_thread')
          ? `${n('reversals_in_other_thread')} of ${n('reversals')} reversals were made in a different conversation from the decision they reversed, and it reads one conversation at a time. It recorded ${n('reversals') - n('reversals_found_as_made')} of them only as “the earlier decision was reversed”, not as the new decision.`
          : '',
        n('made_outside_labels')
          ? `Most of the ${n('made_outside_labels')} other items it called decisions are promises, the kickoff and work reported done: it counts “I’ll have it done by Monday” as a decision to act, where the labels file it as a commitment.`
          : '',
      ].filter(Boolean);
    case 'commitment-tracker':
      return [
        n('due_right') < n('found')
          ? `${n('found') - n('due_right')} of the ${n('found')} due dates it gave are wrong, for one reason: when a message names both a weekday and a date, as in “by Friday 13 February”, its date resolver takes the next such weekday and ignores the date. Said on 2 February, that became 6 February. This walkthrough found the bug; its held-out threads did not.`
          : '',
        n('done_in_other_thread')
          ? `${n('done_in_other_thread')} of the ${n('done_planted')} promises that were kept were confirmed done in a different conversation, which it cannot see when it reads one at a time, so it left them open.`
          : '',
      ].filter(Boolean);
    case 'risk-finder':
      return n('came_true_in_other_thread')
        ? [
            `${n('came_true_in_other_thread')} of the ${n('came_true')} risks that came true were reported in a different conversation from the risk. It reported each as a separate live issue and left the original risk open, because it reads one conversation at a time.`,
          ]
        : [];
    case 'gap-finder':
      return n('outside_on_lookalikes')
        ? [
            `${n('outside_on_lookalikes')} of its other questions come from messages planted as look-alikes for decisions: options listed without choosing, and doubts. Read as questions, they are fair ones; the labels simply do not count them.`,
          ]
        : [];
    case 'expertise-finder':
      return n('outside_on_lookalikes')
        ? [`${n('outside_on_lookalikes')} of its other credits are for laying out options, which the labels do not count as expertise.`]
        : [];
    default:
      return [];
  }
}

// What we found by reading the outputs, beyond what the counts show. Written for this run only: the build stops if
// run.json comes from a different run, so these lines cannot drift away from the files they describe.
const NOTES_FOR_RUN = { seed: 23, spent_usd: 2.015688 };
if (S.seed !== NOTES_FOR_RUN.seed || data.ledger.spent_usd !== NOTES_FOR_RUN.spent_usd) {
  throw new Error('run.json is from a different run than the ledger notes were written for; reread the outputs and update them.');
}
const RUN_NOTES: { who: string; text: string }[] = [
  {
    who: 'org-generator',
    text: 'wrote a fact it had been told to rule out. The plan said annual contracts only, ruling out prices 10% below Ireland; the message it wrote says “Pricing goes 10% below Ireland for year one.” decision-extractor and the second brief then report that as decided. They read the text correctly; the text was wrong.',
  },
  {
    who: 'commitment-tracker',
    text: 'resolves “by Friday 13 February” to the Friday after the message, not to 13 February. All six due dates are wrong, and the wrong dates appear in both briefs.',
  },
  {
    who: 'decision-extractor, commitment-tracker, risk-finder',
    text: 'read one conversation at a time, so a change made in another conversation (a reversal, a promise kept, a risk that came true) is not joined to what it changes. The hosting reversal on 2 March was recorded as “the earlier decision was reversed”, not as the decision to keep everything in Dublin.',
  },
  {
    who: 'commitment-tracker, inside the second brief',
    text: 'marked the employer-of-record shortlist “cancelled”. It slipped from 6 April to 27 April and was never delivered: overdue, not cancelled.',
  },
  {
    who: 'redactor',
    text: 'took three message ids for email addresses. Harmless here, but a false positive all the same.',
  },
  {
    who: 'contradiction-detector',
    text: 'gave different answers on the same record. Run on its own, it reported the Frankfurt conflict; run again inside the second brief, it reported only the changes of plan, so the second brief has no conflicts section.',
  },
  {
    who: 'normalizer',
    text: 'moved the sign-off name (“Mateo”, “Sven”) into the signature in 13 of 43 emails. No sentence was lost, but the body is not exactly what the person wrote.',
  },
];

const STEPS: { n: string; id: string; title: string; pieces: string; state: EvidenceState }[] = [
  { n: '01', id: 'raw', title: 'Raw material arrives', pieces: 'org-generator', state: 'Working prototype' },
  { n: '02', id: 'record', title: 'The record is made legible', pieces: 'normalizer, identity-resolver', state: 'Working prototype' },
  { n: '03', id: 'finders', title: 'Six finders read it', pieces: 'decision-extractor, commitment-tracker, risk-finder, gap-finder, contradiction-detector, expertise-finder', state: 'Working prototype' },
  { n: '04', id: 'layer', title: 'The layer holds what they found', pieces: 'Files on disk today; the layer itself is not built', state: 'Thesis' },
  { n: '05', id: 'brief', title: 'One page for the next decision', pieces: 'brief-writer', state: 'Working prototype' },
  { n: '06', id: 'outcome', title: 'The outcome comes back', pieces: 'A second brief is real; the loop is not built', state: 'Thesis, illustrative' },
  { n: '07', id: 'ledger', title: 'The ledger', pieces: 'The chain, end to end', state: 'Early-stage R&D' },
];

const SECTION_TITLES: Record<string, string> = {
  summary: 'Summary',
  decisions: 'Decisions',
  commitments: 'Commitments',
  conflicts: 'Unresolved conflicts',
  open_questions: 'Open questions',
};

const KIND_LABELS: Record<string, string> = { EMAIL: 'email addresses', PHONE: 'phone numbers', PERSON: 'names', SECRET: 'secrets' };

const WORDS = ['no', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'];

function words(n: number): string {
  return WORDS[n] ?? String(n);
}

function pretty(value: unknown, keys: string[]): string {
  const v = value as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const k of keys) if (v?.[k] !== undefined && v?.[k] !== '') out[k] = v[k];
  return JSON.stringify(out, null, 2);
}

function shown(rows: ScoreRow[] | undefined, missing = true) {
  return (rows ?? []).filter((r) => (missing ? !(r.found && r.found.length) : true));
}

function BriefView({ brief, id }: { brief: Brief; id: string }) {
  const notes: Citation[] = [];
  const index = new Map<string, number>();
  const mark = (c: Citation) => {
    const key = `${c.message_id}|${c.quote}`;
    if (!index.has(key)) {
      notes.push(c);
      index.set(key, notes.length);
    }
    return index.get(key) as number;
  };
  const sections = Object.entries(SECTION_TITLES).filter(([s]) => (brief.sections[s] ?? []).length);
  return (
    <div className="wt-brief" id={id}>
      <div className="wt-brief-page">
        <span className="system-label">
          Brief · {brief.source_count} sources{brief.period ? ` · ${brief.period.from.slice(0, 10)} to ${brief.period.to.slice(0, 10)}` : ''}
        </span>
        <h3>{brief.title}</h3>
        {sections.map(([s, title]) => (
          <div key={s} className="wt-brief-section">
            <h4 className="system-label">
              {title}
              {brief.filled_by?.[s] ? <span> · from {brief.filled_by[s]}</span> : null}
            </h4>
            <ol>
              {(brief.sections[s] as BriefItem[]).map((item, i) => (
                <li key={i}>
                  {item.text}
                  {[item.owner && `owner: ${item.owner}`, item.due && `due: ${item.due}`, item.status && `status: ${item.status}`]
                    .filter(Boolean)
                    .join(', ') ? (
                    <span className="wt-brief-meta">
                      {' '}
                      (
                      {[item.owner && `owner: ${item.owner}`, item.due && `due: ${item.due}`, item.status && `status: ${item.status}`]
                        .filter(Boolean)
                        .join(', ')}
                      )
                    </span>
                  ) : null}{' '}
                  {item.citations.map((c) => (
                    <a key={`${c.message_id}${c.quote}`} className="wt-ref" href={`#${id}-src-${mark(c)}`}>
                      [{mark(c)}]
                    </a>
                  ))}
                </li>
              ))}
            </ol>
          </div>
        ))}
      </div>
      <ol className="wt-brief-sources" aria-label="Sources">
        {notes.map((c, i) => (
          <li key={i} id={`${id}-src-${i + 1}`}>
            <span className="system-label">[{i + 1}]</span>
            <Source c={c} />
          </li>
        ))}
      </ol>
    </div>
  );
}

export default function WalkthroughPage() {
  const totalQuotes = Object.values(F).reduce(
    (n, f) => n + f.items.reduce((m, i) => m + (i.citations?.length ?? 0) + (i.status_citations?.length ?? 0), 0),
    0,
  );
  const generation = data.calls['org-generator'];
  const callTotals = Object.entries(data.calls).filter(([k]) => k !== 'org-generator').map(([, c]) => c).reduce(
    (t, c) => ({ calls: t.calls + c.calls, prompt: t.prompt + c.prompt_tokens, completion: t.completion + c.completion_tokens, cost: t.cost + c.cost_usd }),
    { calls: 0, prompt: 0, completion: 0, cost: 0 },
  );
  const allCalls = Object.values(data.calls).reduce(
    (t, c) => ({ calls: t.calls + c.calls, prompt: t.prompt + c.prompt_tokens, completion: t.completion + c.completion_tokens }),
    { calls: 0, prompt: 0, completion: 0 },
  );
  const models = [...new Set(Object.entries(data.calls).filter(([k]) => k !== 'org-generator').flatMap(([, c]) => c.models))];
  const ns = data.normalizer.by_source ?? {};
  const exact = Object.values(ns).reduce((n, s) => n + num(s.exact), 0);
  const idScore = data.identity.score ?? {};
  const cutBrief = data.briefs.cut;
  const fullBrief = data.briefs.full;
  const lead = (S as unknown as { lead?: { name: string; role: string } }).lead;
  const goal = (S as unknown as { goal?: string }).goal;
  const runDate = (S as unknown as { run_date?: string }).run_date ?? data.generated_at.slice(0, 10);
  const redactedKinds = Object.entries(data.redact.replaced ?? {});
  const messageIdHits = (data.redact.values ?? []).filter((v) => v.is_message_id).length;
  const outcomeIds = new Set([data.outcome.decision?.message_id, data.outcome.outcome?.message_id].filter(Boolean));
  const carried = fullBrief
    ? Object.entries(fullBrief.sections).flatMap(([s, items]) =>
        items.filter((i) => i.citations.some((c) => outcomeIds.has(c.message_id))).map((i) => ({ s, i })),
      )
    : [];

  return (
    <>
      <a className="skip-link" href="#main-content">
        Skip to content
      </a>

      <SiteHeader />

      <main id="main-content" className="wt-page">
        <section className="pov-hero" aria-labelledby="wt-title">
          <div className="pov-hero-grid">
            <div className="hero-label system-label">
              <span>Intellumia / The Lab / Walkthrough</span>
              <span>Run {runDate}</span>
            </div>
            <h1 id="wt-title">
              From the record
              <br />
              <em>to the decision.</em>
            </h1>
            <div className="pov-hero-copy">
              <p>
                {S.company} does not exist. Our organisation generator wrote {words(S.months)} months of its email, chat and
                meetings, with every decision, commitment, risk and question planted as a label we can check against. We
                ran the pieces of the layer on it, one after another. This page shows what each one produced, beside the
                exact text it came from, including what it missed and what it got wrong.
              </p>
              <p>
                Everything here is code we have written and are testing, not a finished product. No client’s information
                is used anywhere. Where a step is not built yet, the page says so and marks it as a thesis. Every number
                was either measured on this run or is quoted from a component’s held-out benchmark, and says which.
              </p>
            </div>
          </div>
          <aside className="pov-status" aria-label="Status of this walkthrough">
            <span className="system-label">Status</span>
            <p>Early-stage R&amp;D: synthetic data, the first run end to end. Each piece is a working prototype.</p>
            <span>
              Run {runDate}.<br />
              Model calls cost {usd(data.ledger.spent_usd)}.
            </span>
          </aside>
        </section>

        <section className="lab-group wt-steps" aria-labelledby="wt-steps-title">
          <div className="section-number system-label">The seven steps, and how proven each one is</div>
          <div className="lab-intro">
            <h2 id="wt-steps-title">One company, followed from its raw messages to one decision and back.</h2>
            <p>
              Each step names the pieces it ran and its evidence state, written as it stands today. A working prototype is
              real, running code; it is not a product. A thesis is a position we hold, with nothing built or tested yet.
            </p>
          </div>
          <ol className="wt-sequence">
            {STEPS.map((s) => (
              <li key={s.id}>
                <a href={`#${s.id}`}>
                  <span className="system-label">{s.n}</span>
                  <strong>{s.title}</strong>
                  <span className="wt-sequence-pieces">{s.pieces}</span>
                </a>
                <Chip state={s.state} />
              </li>
            ))}
          </ol>
        </section>

        {/* 01 */}
        <section className="lab-group lab-alt wt-step" id="raw" aria-labelledby="raw-title">
          <div className="section-number system-label">01 / Raw material arrives</div>
          <div className="lab-intro">
            <h2 id="raw-title">
              {S.generated.total} messages over {words(S.months)} months, in three channels.
            </h2>
            <p>
              {S.company} has {words(S.people.length)} people. Its {S.projects[0]} project
              {goal ? <> sets out to {goal}</> : null}, led by {lead ? `${lead.name}, ${lead.role}` : 'its project lead'}. Messages
              run from {S.first} to {S.last}. org-generator decided every event in code from seed {S.seed}; a model then
              wrote the words, each person keeping one writing habit.
            </p>
            <Chip state="Working prototype" />
          </div>
          <div className="wt-body">
            <table className="wt-table">
              <thead>
                <tr>
                  <th className="system-label">Channel</th>
                  <th className="system-label">Messages</th>
                  <th className="system-label">Conversations</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Email</td>
                  <td>{S.generated.email}</td>
                  <td>{count(S.threads.email, 'thread')}</td>
                </tr>
                <tr>
                  <td>Chat</td>
                  <td>{S.generated.chat}</td>
                  <td>{count(S.threads.chat, 'thread')}</td>
                </tr>
                <tr>
                  <td>Meetings</td>
                  <td>{count(S.generated.meeting_turns, 'turn')}</td>
                  <td>{count(S.threads.meetings, 'meeting')}</td>
                </tr>
                <tr>
                  <td>Documents</td>
                  <td>0</td>
                  <td>org-generator does not write documents yet</td>
                </tr>
              </tbody>
            </table>
            <p className="wt-note">
              Planted in the timeline, for checking later: {num(S.labels.decisions)} decisions, {num(S.labels.decision_links)}{' '}
              reaffirmations and reversals, {num(S.labels.commitments)} commitments, {num(S.labels.risks)} risks,{' '}
              {num(S.labels.questions)} questions, {num(S.labels.expertise)} explanations, {num(S.labels.outcomes)} outcomes and{' '}
              {num(S.labels.lookalikes)} look-alikes: options listed without deciding, doubts and ideas nobody took up. No
              component sees these labels. {S.fallbacks ? `${count(S.fallbacks, 'planted fact')} could not be written by the model and fell back to plain text.` : 'Every planted fact was written by the model; none fell back to plain text.'}
            </p>
            <div className="wt-raw-grid">
              {data.examples.email ? <Pre label="Email, as exported (mbox, body only)">{data.examples.email.raw}</Pre> : null}
              {data.examples.chat ? (
                <Pre label="Chat, as exported (Slack JSON)">{JSON.stringify(data.examples.chat.raw, null, 2)}</Pre>
              ) : null}
              {data.examples.meeting ? (
                <Pre label={`Meeting, as exported (${data.examples.meeting.file})`}>{data.examples.meeting.raw}</Pre>
              ) : null}
            </div>
            <p className="wt-note">
              One disclosure. org-generator writes its messages already in the normalizer’s format, so there is no raw
              export to start from. A script of ours, render.py, writes them back the way tools export them: an mbox with
              signatures and quoted history, a Slack export without email addresses, WebVTT captions. It adds those
              wrappers and never changes what a person wrote. Phone numbers in signatures come from the UK range reserved
              for drama.
            </p>
            {EM_DASHES_SHOWN_AS_HYPHENS ? (
              <p className="wt-note">
                This site sets no em dashes. Where a message, or something a component wrote about it, contains one, it is
                shown on this page as a spaced hyphen ({count(EM_DASHES_SHOWN_AS_HYPHENS, 'place', 'places')}). The run’s own
                files keep the original text, and nothing else in any quote is changed.
              </p>
            ) : null}
            <p className="wt-bench">
              <span className="system-label">Held-out benchmark, org-generator</span>
              252 of 253 planted facts were judged present in the text of two held-out organisations. A judge picked the
              real Enron email thread over a generated one 55% of the time (50% means it cannot tell), with about ±15
              points of uncertainty.
            </p>
          </div>
        </section>

        {/* 02 */}
        <section className="lab-group wt-step" id="record" aria-labelledby="record-title">
          <div className="section-number system-label">02 / The record is made legible</div>
          <div className="lab-intro">
            <h2 id="record-title">
              One format, and {count(num(idScore.people_found), 'person', 'people')} instead of{' '}
              {count(data.identity.sender_ids.length, 'identity', 'identities')}.
            </h2>
            <p>
              normalizer turns each export into the same threaded message, keeping only what the sender newly wrote.
              identity-resolver then works out which address, chat account and speaker name belong to the same person,
              and records why.
            </p>
            <Chip state="Working prototype" />
          </div>
          <div className="wt-body">
            <div className="wt-switch">
              <fieldset className="wt-picker">
                <legend className="system-label">The same message, before and after</legend>
                {(['email', 'chat', 'meeting'] as const)
                  .filter((k) => data.examples[k])
                  .map((k, i) => (
                    <span key={k} className="wt-pick-wrap">
                      <input type="radio" name="wt-example" id={`wt-x-${k}`} className="wt-radio" defaultChecked={i === 0} />
                      <label htmlFor={`wt-x-${k}`} className="wt-pick">
                        {k === 'email' ? 'Email' : k === 'chat' ? 'Chat' : 'Meeting'}
                      </label>
                    </span>
                  ))}
              </fieldset>
              {data.examples.email ? (
                <div className="wt-pair" data-for="email">
                  <Pre label="Before: as exported">
                    {`From: ${data.examples.email.headers.from}\nSubject: ${data.examples.email.headers.subject}\nMessage-ID: ${data.examples.email.headers.message_id}\n\n${data.examples.email.raw}`}
                  </Pre>
                  <Pre label="After: normalizer">
                    {pretty(data.examples.email.normalised, ['id', 'source', 'sender', 'sent_at', 'thread_id', 'parent_id', 'body', 'signature', 'quoted'])}
                  </Pre>
                </div>
              ) : null}
              {data.examples.chat ? (
                <div className="wt-pair" data-for="chat">
                  <Pre label="Before: as exported">{JSON.stringify(data.examples.chat.raw, null, 2)}</Pre>
                  <Pre label="After: normalizer">
                    {pretty(data.examples.chat.normalised, ['id', 'source', 'sender', 'sent_at', 'thread_id', 'parent_id', 'channel', 'body'])}
                  </Pre>
                </div>
              ) : null}
              {data.examples.meeting ? (
                <div className="wt-pair" data-for="meeting">
                  <Pre label="Before: as exported">{data.examples.meeting.raw}</Pre>
                  <Pre label="After: normalizer">
                    {pretty(data.examples.meeting.normalised, ['id', 'source', 'sender', 'sent_at', 'thread_id', 'start_seconds', 'end_seconds', 'body'])}
                  </Pre>
                </div>
              ) : null}
              <p className="wt-note">How these were chosen: {data.examples.rule}</p>
            </div>

            <Tally
              rows={[
                [`${exact} of ${data.normalizer.generated_messages}`, 'messages where normalizer kept exactly what the person wrote'],
                [`${Object.values(ns).reduce((n, s) => n + num(s.signoff_moved), 0)}`, 'where only the sign-off name went to the signature'],
                [`${Object.values(ns).reduce((n, s) => n + num(s.own_text_lost) + num(s.extra_text_left), 0)}`, 'with words cut, or quoted history or a signature left in'],
                [`${num(idScore.wrong_merges)}`, 'people merged who are different people'],
              ]}
            />

            <table className="wt-table wt-people">
              <thead>
                <tr>
                  <th className="system-label">Person</th>
                  <th className="system-label">Appears in the record as</th>
                  <th className="system-label">Joined by</th>
                </tr>
              </thead>
              <tbody>
                {data.identity.people.map((p) => (
                  <tr key={p.name}>
                    <td>
                      <strong>{p.name}</strong>
                      {p.role ? <span>{p.role}</span> : null}
                    </td>
                    <td>{p.appears_as.join(' · ')}</td>
                    <td>
                      {Object.keys(p.evidence_kinds).length
                        ? Object.entries(p.evidence_kinds)
                            .map(([k, n]) => `${k.replaceAll('_', ' ')} (${n})`)
                            .join(', ')
                        : 'one way only'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p className="wt-note">
              This is the easy case, and we say so: every source showed people’s full names, so the rules joined everyone
              without a model. identity-resolver links {num(idScore.pairs_right)} of {num(idScore.pairs_true)} pairs of
              identities that belong together here, with {num(idScore.wrong_merges)} wrong merges.
            </p>
            <p className="wt-bench">
              <span className="system-label">Held-out benchmarks</span>
              normalizer, on 978 real Enron replies: the body came out exactly right in 71.0%, against 46.3% for the next
              best open tool, and it loses slightly more of the sender’s own text (0.8% against 0.5%). identity-resolver,
              on 40 generated organisations: pairwise F1 86.5% with rules alone and 99.5% with a model for the pairs the
              rules leave apart, with no wrong merges; on real Enron mail headers, 87.1% and 88.9%.
            </p>
          </div>
        </section>

        {/* 03 */}
        <section className="lab-group lab-alt wt-step" id="finders" aria-labelledby="finders-title">
          <div className="section-number system-label">03 / Six finders read it</div>
          <div className="lab-intro">
            <h2 id="finders-title">Six questions, each answered with the words people actually wrote.</h2>
            <p>
              Each finder reads the record on its own and must quote the message every item comes from. An item whose
              quote cannot be found in the record is dropped. For each: what it found beside its source, what it missed,
              what it reported that the planted labels do not hold, and its held-out benchmark. Counts are for this run
              only, on one fictional company: they are not a benchmark.
            </p>
            <Chip state="Working prototype" />
          </div>
          <div className="wt-body wt-finders">
            <fieldset className="wt-picker">
              <legend className="system-label">Pick a finder</legend>
              {FINDERS.map((f, i) => (
                <span key={f.id} className="wt-pick-wrap">
                  <input type="radio" name="wt-finder" id={`wt-f-${f.id}`} className="wt-radio" defaultChecked={i === 0} />
                  <label htmlFor={`wt-f-${f.id}`} className="wt-pick">
                    {f.id}
                  </label>
                </span>
              ))}
            </fieldset>
            {FINDERS.map((f) => {
              const fd = F[f.id];
              if (!fd) return null;
              const s = fd.score;
              const misses = f.id === 'contradiction-detector'
                ? (s.changes ?? []).filter((ch) => !(s.items ?? []).some((it) => ((it as { matches_change?: string[] }).matches_change ?? []).includes(ch.id as string)))
                : shown(s.rows);
              const wrong = [...(s.lookalikes ?? []), ...(s.outside ?? [])];
              return (
                <Panel key={f.id} id={f.id}>
                  <header className="wt-panel-head">
                    <h3 id={`wt-panel-${f.id}`}>{f.id}</h3>
                    <p>{f.question}</p>
                    <span className="system-label">
                      Read {f.read} · {count(fd.items.length, 'item')} reported
                      {fd.calls ? ` · ${count(fd.calls.calls, 'model call')}, ${usd(fd.calls.cost_usd)}` : ''}
                    </span>
                  </header>
                  <Tally rows={tallies(f.id, fd)} />
                  {finderNotes(f.id).map((note) => (
                    <p key={note} className="wt-note">
                      {note}
                    </p>
                  ))}

                  <h4 className="system-label wt-subhead">Planted items it found, beside its source</h4>
                  {fd.items.filter((i) => i.matched).slice(0, 3).map((item: Item) => (
                    <ItemView key={item.id} finder={f.id} item={item} />
                  ))}
                  {fd.items.filter((i) => i.matched).length === 0 ? <p className="wt-note">None.</p> : null}
                  <p className="wt-note">
                    Shown: up to three of the {fd.items.filter((i) => i.matched).length} items that match a planted label,
                    those about the hosting decision first. Every item it reported is listed at the end of this panel.
                  </p>

                  <h4 className="system-label wt-subhead">What it missed</h4>
                  {misses.length === 0 ? (
                    <p className="wt-note">Nothing planted was missed.</p>
                  ) : (
                    misses.map((row, i) => <Planted key={i} row={row} what="Planted, not found" />)
                  )}

                  <h4 className="system-label wt-subhead">What it reported that the labels do not hold</h4>
                  {wrong.length === 0 ? (
                    <p className="wt-note">Nothing.</p>
                  ) : (
                    <>
                      {wrong.slice(0, 3).map((item, i) => (
                        <div key={i} className="wt-wrong">
                          <p>
                            <strong>{String(item.statement ?? item.question ?? item.topic ?? '')}</strong>
                            <span className="system-label">
                              {(s.lookalikes ?? []).includes(item) ? 'Look-alike: a false positive by construction' : `Cites: ${kinds(item.cites_kinds)}`}
                            </span>
                          </p>
                          {((item.evidence as Citation[]) ?? []).slice(0, f.id === 'contradiction-detector' ? 2 : 1).map((c, j) => (
                            <Source key={j} c={c} />
                          ))}
                        </div>
                      ))}
                      {wrong.length > 3 ? <p className="wt-note">And {wrong.length - 3} more, listed below.</p> : null}
                      <p className="wt-note">
                        The labels do not hold everything that is true in the text, so not all of these are mistakes. The
                        message kinds each one cites are shown, so you can judge from the quote.
                      </p>
                    </>
                  )}

                  <details className="wt-all">
                    <summary>Every item {f.id} reported ({fd.items.length})</summary>
                    <ol>
                      {fd.items.map((item) => (
                        <li key={item.id}>
                          <strong>{FIELDS[f.id].headline.map((k) => {
                            const v = item[k] as unknown;
                            return typeof v === 'object' && v ? String((v as { name?: string }).name ?? '') : String(v ?? '');
                          }).filter(Boolean).join(': ')}</strong>
                          {item.status ? <span className="system-label"> {String(item.status)}</span> : null}
                          {(item.citations ?? []).slice(0, 1).map((c, j) => (
                            <Source key={j} c={c} />
                          ))}
                        </li>
                      ))}
                    </ol>
                  </details>

                  <div className="wt-bench">
                    <span className="system-label">Held-out benchmark, from its RESULTS.md</span>
                    {f.benchmark.map((b) => (
                      <p key={b}>{b}</p>
                    ))}
                  </div>
                </Panel>
              );
            })}
          </div>
        </section>

        {/* 04 */}
        <section className="lab-group lab-dark wt-step" id="layer" aria-labelledby="layer-title">
          <div className="section-number system-label">04 / The layer holds what they found</div>
          <div className="lab-intro">
            <h2 id="layer-title">What the layer would hold, and what holds it today.</h2>
            <p>
              The finders wrote their records to plain files, every record with its quote. That is the raw material of an
              intelligence layer: evidence, memory and decisions, owned by the company. The layer itself, with permissions
              and an owner, is not built.
            </p>
            <Chip state="Thesis" />
          </div>
          <div className="wt-body">
            <div className="wt-layer">
              <div>
                <span className="system-label">Evidence</span>
                <strong>{count(totalQuotes, 'quote')}</strong>
                <p>Each located in the record by intellumia-core before it was kept. Today: one file per finder.</p>
                <Chip state="Working prototype" />
              </div>
              <div>
                <span className="system-label">Memory</span>
                <strong>
                  {count(F['commitment-tracker']?.items.length ?? 0, 'commitment')}, {count(F['risk-finder']?.items.length ?? 0, 'risk or issue', 'risks and issues')},{' '}
                  {count(F['gap-finder']?.items.length ?? 0, 'question')}, {count(F['expertise-finder']?.items.length ?? 0, 'credit')} for who knows what
                </strong>
                <p>What the company has promised, feared, asked and shown it knows, each with its source.</p>
                <Chip state="Working prototype" />
              </div>
              <div>
                <span className="system-label">Decisions</span>
                <strong>{count(F['decision-extractor']?.items.length ?? 0, 'decision record')}</strong>
                <p>Status, owner and reason where the record states them. Nothing yet links a decision to what followed.</p>
                <Chip state="Working prototype" />
              </div>
              <div>
                <span className="system-label">Permissions</span>
                <strong>Who may see what</strong>
                <table className="wt-table wt-perm">
                  <tbody>
                    <tr>
                      <td>Leadership</td>
                      <td>Decisions, outcomes and open risks, across projects</td>
                    </tr>
                    <tr>
                      <td>The project team</td>
                      <td>The full record of its own channels</td>
                    </tr>
                    <tr>
                      <td>A model, for one task</td>
                      <td>Only what that task needs, through the control point</td>
                    </tr>
                  </tbody>
                </table>
                <p>Illustrative. Nothing enforced permissions in this run: every component read everything.</p>
                <Chip state="Thesis, illustrative" />
              </div>
            </div>

            <h3 className="wt-h3">What left for the model</h3>
            <Tally
              rows={[
                [String(callTotals.calls), callTotals.calls === 1 ? 'request to a model, logged with its reply' : 'requests to a model, every one logged with its reply'],
                [callTotals.prompt.toLocaleString('en-GB'), 'tokens sent'],
                [callTotals.completion.toLocaleString('en-GB'), 'tokens received'],
                [usd(callTotals.cost), 'what the logged calls cost'],
              ]}
            />
            <p className="wt-note">
              These are the components’ calls, all to {models.join(', ') || 'no model'} through OpenRouter. Writing the
              fictional company took {generation ? `${count(generation.calls, 'more call')}, ${usd(generation.cost_usd)}` : 'separate calls'}, not counted here.
            </p>
            {data.redact.sent ? (
              <>
                <p>
                  We ran redactor, on its patterns only, over the exact text {data.redact.component} sent in one call: the
                  call with the most @ signs in it, where addresses would show. It replaced{' '}
                  {redactedKinds.length ? redactedKinds.map(([k, n]) => `${n} ${KIND_LABELS[k] ?? k.toLowerCase()}`).join(', ') : 'nothing'}
                  {messageIdHits ? `, and ${messageIdHits === (data.redact.values ?? []).length ? 'every one of them' : count(messageIdHits, 'of them', 'of them')} is a message id such as ${(data.redact.values ?? [])[0]?.text}, which has the shape of an email address. A false positive: there was no address in what was sent, because normalizer had already set signatures aside` : ''}.
                  It left the names alone: names need its local model, which downloads from Hugging Face, and this run could
                  not reach it.
                </p>
                <div className="wt-raw-grid wt-two">
                  <Pre label="Sent to the model (excerpt)">{(data.redact.sent ?? '').slice(0, 1200)}</Pre>
                  <Pre label="After redactor, patterns only (same excerpt)">{(data.redact.redacted ?? '').slice(0, 1200)}</Pre>
                </div>
              </>
            ) : null}
            <p className="wt-note">
              In this run nothing was redacted before it left: the company is fictional, and redactor is not yet wired
              between the finders and the model. egrysa, the policy checkpoint, was not run.
            </p>
            <p className="wt-bench">
              <span className="system-label">Held-out benchmark, redactor</span>
              On 1,000 synthetic Nemotron-PII documents, patterns alone missed 67.9% of sensitive values; with its local
              name model, 3.1%, against 33.1% for Microsoft Presidio.
            </p>
          </div>
        </section>

        {/* 05 */}
        <section className="lab-group wt-step" id="brief" aria-labelledby="brief-title">
          <div className="section-number system-label">05 / One page for the next decision</div>
          <div className="lab-intro">
            <h2 id="brief-title">One page for the person about to make the call.</h2>
            <p>
              On {data.outcome.decision?.when ?? 'the day of the meeting'}, {lead ? lead.name : 'the project lead'} chairs the weekly meeting where hosting is decided
              again. brief-writer read the record up to the night before
              {cutBrief ? `, ${count(cutBrief.source_count, 'message')}` : ''}. Its decisions, commitments and conflicts
              come from decision-extractor, commitment-tracker and contradiction-detector; the summary and open questions
              are its own. Every line cites the text it rests on.
            </p>
            <Chip state="Working prototype" />
          </div>
          <div className="wt-body">
            {cutBrief ? <BriefView brief={cutBrief} id="wt-brief-cut" /> : <p className="wt-note">No brief in this run.</p>}
            <p className="wt-note">
              brief-writer does not take a question. It briefs everything it is given; we gave it the record up to 1 March
              and a title naming the decision. A brief framed around one pending decision is not built.
            </p>
            <p className="wt-note">
              Read it as Tariq would, and check it. The due dates in its commitments come from commitment-tracker and carry
              its date bug: “by Friday 13 February” shows as due 2026-02-06. Several of its decisions are promises. The
              conflict it raises, Frankfurt ruled out and then built, is real and nobody planted it.
            </p>
            <p className="wt-bench">
              <span className="system-label">Held-out benchmark, brief-writer</span>
              On 60 AMI meetings, 4.2% and 2.5% of its items were not supported by the transcript under two judges, against
              7.5% and 7.9% for a plain prompt. Its coverage of the human summary there is behind: 62.4% and 67.8%, against
              64.4% and 72.2%.
            </p>
          </div>
        </section>

        {/* 06 */}
        <section className="lab-group lab-alt wt-step" id="outcome" aria-labelledby="outcome-title">
          <div className="section-number system-label">06 / The outcome comes back</div>
          <div className="lab-intro">
            <h2 id="outcome-title">What happened next, and whether the next brief knows it.</h2>
            <p>
              The decision and its result are in the record, because the generator planted them. Whether a later brief
              carries them forward is something we can check.
            </p>
            <Chip state="Thesis, illustrative" />
          </div>
          <div className="wt-body">
            <div className="wt-raw-grid wt-two">
              {data.outcome.decision ? (
                <div>
                  <span className="system-label wt-item-label">The decision, at that meeting</span>
                  <Source c={data.outcome.decision} />
                </div>
              ) : null}
              {data.outcome.outcome ? (
                <div>
                  <span className="system-label wt-item-label">How it turned out</span>
                  <Source c={data.outcome.outcome} />
                </div>
              ) : null}
            </div>
            <p>
              A second brief, written by brief-writer on the whole record
              {fullBrief ? ` (${count(fullBrief.source_count, 'message')})` : ''},{' '}
              {data.outcome.outcome?.cited_by_full_brief ? 'cites the outcome.' : 'does not cite the outcome.'}{' '}
              {data.outcome.decision?.cited_by_full_brief ? 'It cites the decision.' : 'It does not cite the decision.'}{' '}
              {carried.length ? 'These are its lines that rest on them:' : ''}
            </p>
            {carried.map(({ s, i }, n) => (
              <div key={n} className="wt-carried">
                <span className="system-label">{SECTION_TITLES[s]}</span>
                <p>{i.text}</p>
                {i.citations.map((c, j) => (
                  <Source key={j} c={c} />
                ))}
              </div>
            ))}
            <figure className="wt-loop" aria-label="Illustrative: how the layer would hold the outcome">
              <div className="wt-loop-node wt-solid">
                <span className="system-label">Decision</span>
                {data.outcome.decision?.when ?? ''}
              </div>
              <div className="wt-loop-edge wt-dashed" aria-hidden="true" />
              <div className="wt-loop-node wt-hollow">
                <span className="system-label">Outcome, stored against it</span>
                {data.outcome.outcome?.when ?? ''}
              </div>
              <div className="wt-loop-edge wt-dashed" aria-hidden="true" />
              <div className="wt-loop-node wt-hollow">
                <span className="system-label">The next call starts here</span>
                Hosting, again
              </div>
              <figcaption className="wt-note">
                Thesis, illustrative. In the layer, the outcome would be kept against the decision it judges, so the next
                decision on hosting starts from it whether or not anyone writes it down again. Nothing does that today: a
                brief finds the outcome only if the message is in what it reads. Solid: in this run. Dashed and hollow:
                not built.
              </figcaption>
            </figure>
            {fullBrief ? (
              <details className="wt-all">
                <summary>The whole second brief</summary>
                <BriefView brief={fullBrief} id="wt-brief-full" />
              </details>
            ) : null}
          </div>
        </section>

        {/* 07 */}
        <section className="lab-group lab-dark wt-step" id="ledger" aria-labelledby="ledger-title">
          <div className="section-number system-label">07 / The ledger</div>
          <div className="lab-intro">
            <h2 id="ledger-title">What went wrong, what is not built, and how proven each step is.</h2>
            <p>Written as it stands today, without rounding up.</p>
            <Chip state="Early-stage R&D" />
          </div>
          <div className="wt-body">
            <table className="wt-table wt-ledger">
              <thead>
                <tr>
                  <th className="system-label">Step</th>
                  <th className="system-label">Pieces</th>
                  <th className="system-label">Evidence state</th>
                </tr>
              </thead>
              <tbody>
                {STEPS.map((s) => (
                  <tr key={s.id}>
                    <td>
                      {s.n} {s.title}
                    </td>
                    <td>{s.pieces}</td>
                    <td>
                      <Chip state={s.state} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            <h3 className="wt-h3">What went wrong in this run</h3>
            <ul className="wt-rows">
              {FINDERS.map((f) => {
                const fd = F[f.id];
                const short = fd ? shortfalls(f.id, fd) : [];
                return short.length ? (
                  <li key={f.id}>
                    <strong>{f.id}</strong> {short.join('; ')}.
                  </li>
                ) : null;
              })}
              {RUN_NOTES.map((n) => (
                <li key={n.who + n.text.slice(0, 20)}>
                  <strong>{n.who}</strong> {n.text}
                </li>
              ))}
              {S.fallbacks ? (
                <li>
                  <strong>org-generator</strong> could not get the model to write {count(S.fallbacks, 'planted fact')} and used plain text instead.
                </li>
              ) : null}
              {Object.entries(F)
                .filter(([, fd]) => fd.run && fd.run.exit !== 0)
                .map(([id, fd]) => (
                  <li key={`exit-${id}`}>
                    <strong>{id}</strong> stopped with an error: {fd.run?.stderr.join(' ')}
                  </li>
                ))}
            </ul>

            <h3 className="wt-h3">What the labels cannot check</h3>
            <p className="wt-note">
              Items a finder reported that no planted label covers. These are not counted as errors: some are true and
              simply unlabelled, some are not. Each is listed, with its quote, in its finder’s panel.
            </p>
            <ul className="wt-rows">
              {FINDERS.map((f) => {
                const fd = F[f.id];
                const u = fd ? unchecked(f.id, fd) : null;
                return u ? (
                  <li key={f.id}>
                    <strong>{f.id}</strong> {u}.
                  </li>
                ) : null;
              })}
            </ul>

            <h3 className="wt-h3">What is not built</h3>
            <ul className="wt-rows">
              <li>Documents. org-generator writes email, chat and meetings only, so nothing here was read from a document.</li>
              <li>The layer as a system: a store the company owns, with permissions enforced on who and what may read it.</li>
              <li>Keeping an outcome against the decision it judges, so the next decision starts from it.</li>
              <li>A brief framed around one pending decision; brief-writer briefs everything it is given.</li>
              <li>The control point in the path: redactor and egrysa are not wired between the finders and the model.</li>
              <li>A test of identity-resolver on hard cases here: every source showed full names.</li>
              <li>Raw exports from real tools: the ones read here were rendered by us from the generator’s messages.</li>
            </ul>

            <h3 className="wt-h3">What it cost</h3>
            <table className="wt-table wt-spend">
              <thead>
                <tr>
                  <th className="system-label">Piece</th>
                  <th className="system-label">Model calls</th>
                  <th className="system-label">Tokens sent / received</th>
                  <th className="system-label">Cost</th>
                </tr>
              </thead>
              <tbody>
                {Object.entries(data.calls).map(([k, c]) => (
                  <tr key={k}>
                    <td>{k}</td>
                    <td>{c.calls}</td>
                    <td>
                      {c.prompt_tokens.toLocaleString('en-GB')} / {c.completion_tokens.toLocaleString('en-GB')}
                    </td>
                    <td>{usd(c.cost_usd)}</td>
                  </tr>
                ))}
                <tr>
                  <td>
                    <strong>Total, from the shared spending ledger</strong>
                  </td>
                  <td>{allCalls.calls}</td>
                  <td>
                    {allCalls.prompt.toLocaleString('en-GB')} / {allCalls.completion.toLocaleString('en-GB')}
                  </td>
                  <td>
                    <strong>{usd(data.ledger.spent_usd)}</strong>
                  </td>
                </tr>
              </tbody>
            </table>
            <p className="wt-note">
              US dollars, as OpenRouter reported them for each call. Status checks with TypeSafe’s Jev, used by
              decision-extractor and gap-finder, are counted in the ledger but not in the call log.
            </p>

            <h3 className="wt-h3">Run it again</h3>
            <p className="wt-note">
              The run, its harness and every file it wrote are in the org-generator repository, folder walkthrough/.
              Versions: {Object.entries(data.versions)
                .map(([k, v]) => `${k} ${v.version ?? ''}${v.commit ? ` (${v.commit})` : ''}`)
                .join(', ')}
              .
            </p>
          </div>
        </section>

        <section className="conversation-section" aria-labelledby="conversation-title">
          <span className="system-label">Where is your next material decision stuck?</span>
          <h2 id="conversation-title">
            <span>What would you</span>
            <span>check first?</span>
          </h2>
          <Link
            href="/connect"
            className="conversation-link"
            data-analytics-event="conversation_path_open"
            data-analytics-location="walkthrough_conversation"
          >
            Begin a conversation
            <span aria-hidden="true">↗</span>
          </Link>
        </section>
      </main>

      <SiteFooter />
    </>
  );
}
